[build]
  base = "website/"
  command = "yarn build"
  publish = "public/"

[[redirects]]
  from = "/*"
  to = "/bigtest/:splat"

[[headers]]
  for = "/bigtest/asciinema/iframes/cross-platform.html"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
